pipeline{
    agent any
    tools{
        maven 'mymaven'
    }
    environment{
        IMAGE_NAME='kalyanimage'
        IMAGE_TAG="${BUILD_NUMBER}"
        CONTAINER_PORT='8080'
        
    }
    stages{
        stage('Check Out'){
            steps{
                git branch: 'main', url: 'https://github.com/Kalyan9912/Restaurent.git'
            }
        }
        stage('Compile'){
            steps{
                dir('BACKEND'){
                    sh 'mvn clean compile'
                }
                
            }
            
        }
        stage('Package'){
            steps{
                dir('BACKEND'){
                sh 'mvn package'
                }
            }
        }
        stage('Docker Build'){
            steps{
                dir('BACKEND'){
                sh 'docker build -t kalyanimage:${BUILD_NUMBER} .'
                }
            }
                
        }
        stage('Docker Push'){
            steps{
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh """
                        echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin
                        docker tag ${IMAGE_NAME}:${IMAGE_TAG} \$DOCKER_USER/${IMAGE_NAME}:${IMAGE_TAG}
                        docker push \$DOCKER_USER/${IMAGE_NAME}:${IMAGE_TAG}
                    """
                }
            }
        }

        stage('Deploy'){
            steps{
                withCredentials([file(credentialsId: 'kubeconfig-kops', variable: 'KUBECONFIG')]) {
              sh '''
                  export KUBECONFIG=$KUBECONFIG
                  kubectl get nodes
                 '''
}
                dir('BACKEND/kubernetes'){
                    sh """
                        cp deployment.yml deployment-temp.yml
                        sed -i 's|IMAGE_TAG|${IMAGE_TAG}|g' deployment-temp.yml
                        kubectl apply -f deployment-temp.yml
                        kubectl apply -f service.yml
                    """
                }
            }
        }
    }
}
        
            
        
        
