apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-backend
  labels:
    app: restaurant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
        - name: restaurant-container
          image: kalyanimage:IMAGE_TAG
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
